/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebaaethersolutions;

/**
 *
 * @author Familia Sotillo
 */
public class Pregunta4 {

    /* >Problema 4

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors? */
    public void solucion() {
        int triangle = 0;
        int aux = 0;
        int j = 1;
        while (aux < 500) {
            triangle = triangle + j;
            j++;
            aux = 0;
            int raiz = (int) Math.sqrt(triangle);

            for (int i = 1; i <= raiz; i++) {
                if (triangle % i == 0) {
                    aux += 2;
                }
            }
            if (raiz * raiz == triangle) {
                aux--;
            }

            System.out.println(aux);
            //System.out.println(triangle);

        }
        System.out.println("the first triangle number to have over five hundred divisors is: " + triangle + " with " + aux + " divisors");
    }
}
